"""Configuration module for the RAG chatbot."""

from .config import (
    ANTHROPIC_API_KEY,
    MODEL_NAME,
    MONGODB_URI,
    QDRANT_URL,
    QDRANT_COLLECTION_NAME,
    EMBEDDING_MODEL_NAME,
    SIMILARITY_SEARCH_K,
    SIMILARITY_THRESHOLD,
    SYSTEM_PROMPT_TEMPLATE,
)

__all__ = [
    "ANTHROPIC_API_KEY",
    "MODEL_NAME",
    "MONGODB_URI",
    "QDRANT_URL",
    "QDRANT_COLLECTION_NAME",
    "EMBEDDING_MODEL_NAME",
    "SIMILARITY_SEARCH_K",
    "SIMILARITY_THRESHOLD",
    "SYSTEM_PROMPT_TEMPLATE",
]
